# Generated by Django 5.2.8 on 2026-07-13 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_interactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyAssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('triggered_by', models.CharField(choices=[('lab_update', 'Lab Metric Updated'), ('medication_change', 'Medication Cabinet Modified'), ('prescription_parsed', 'Prescription Parsing Completed'), ('manual', 'Manual Safety Check')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_history', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProactiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Low', 'Low')], max_length=20)),
                ('message', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proactive_alerts', to='patients.patientprofile')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.safetyassessmenthistory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
